#Name: elasticsearch
#
#Namespace: kube-system
#
#Image: registry.k8s.io/fluentd-elasticsearch:1.20

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  labels:
     app: fluentd
  namespace: kube-system
spec:
  selector:
      matchLabels:
        app: fluentd
  template:
    metadata:
      name: fluentd
      labels:
        app: fluentd
    spec:
      containers:
        - name: nginx
          image: registry.k8s.io/fluentd-elasticsearch:1.20