---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pv
spec:
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage 
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - mountPath: /var/www/html
      name: html-volume
  volumes:    
    - persistentVolumeClaim:
        claimName: local-pvc
      name: html-volume 

--- 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delayed-volume-sc
provisioner:  kubernetes.io/no-provisioner  # Replace with the appropriate provisioner for your environment
parameters:
  volumeBindingMode: WaitForFirstConsumer 