apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
     app: myapp
     type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx


