apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
     app: myapp
     type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx


